plugin-name: "[VoteForCommand]: "
voting-time: 60 # in seconds

# locales
# please keep spaces as like here initially
vote-won: "Vote has been won! "
vote-failed: "Vote has been failed! "
vote-for: "[FOR]"
vote-against: "[AGAINST]"
already-made-choice: "You already make your choice!"
you-made-choice: "You make your choice! "
new-vote-started: "New vote has been started! "
votes-for: " votes for: "
two-minutes-remaining: "2 minutes remaining!"
sixty-seconds-remaining: "60 seconds remaining!"
thirty-seconds-remaining: "30 seconds remaining!"
ten-seconds-remaining: "10 seconds remaining!"
cannot-start-vote: "You cannot start this vote right now!"

#
votingCommands:
  freeDiamond:
    name: "FREE DIAMOND!!"
    description: "Give a random player diamond!"
    material: "DIAMOND"
    commands:
    - "execute as @r run give @s minecraft:diamond 1"
    cooldown: 3600 # in seconds. 3600s = 1h
    percentToWin: 50.0
    minimumOnline: 5
  heal:
    name: "Sacred blessing"
    description: "Sacred blessing of the goddess of health. All players will receive regeneration."
    commands:
    - "execute as @a at @s run particle minecraft:heart ~ ~1 ~ 0.5 1 0.5 0.1 10"
    - "effect give @a minecraft:glowing 5 0 true"
    - "effect give @a minecraft:regeneration 120 1 true"
    cooldown: 3600 # in seconds. 3600s = 1h
    percentToWin: 70.0
    minimumOnline: 10
